### ISSUE TITLE
One Bot - feature request for room to chatroomid mapping

### ISSUE THREAD

**Issue by daktak** [web-tech-tw/arona#14]
If we can make a database that maps Line chat room Id's to Matrix room id's
Then if the bot is messaged on a new channel, it can lookup the entry and create a new room if it does not exist.
So you could add your matrix username to the config to add to all newly created channels.
You could manual update the database for previously existing or change of mapping.

**Comment by supersonictw** [comment]
Nice idea!
https://github.com/web-tech-tw/matrix-line-bridge

**Comment by daktak** [comment]
https://github.com/web-tech-tw/matrix-line-bridge/commit/e0cd20307f186e7a909e4d98c9240e45ed99a6a6

I was thinking something like this.
If the room mapping doesn't exist. Invite a user (as specified in .env) into a newly created one.

That way you can get any message from Line if the line user knows to talk to your bot.

**Comment by daktak** [comment]
Running #pair !matrixroomname from line, and #pair linechatroomid  from Matrix, are not creating the room mapping entries.

```
Executing (default): SELECT `id`, `lineMode`, `lineHookFrom`, `lineTo`, `matrixTo`, `createdTime`, `updatedTime` FROM `room_map` AS `room_map` WHERE `room_map`.`lineHookFrom` = 'C7d95034fd3e3ec445aea8c48eff42a9e' LIMIT 1;
MatrixHttpClient (REQ-162) { errcode: 'M_FORBIDDEN', error: 'Unknown room' }
Executing (default): SELECT `id`, `lineMode`, `lineHookFrom`, `lineTo`, `matrixTo`, `createdTime`, `updatedTime` FROM `room_map` AS `room_map` WHERE `room_map`.`lineHookFrom` = 'C7d95034fd3e3ec445aea8c48eff42a9e' LIMIT 1;
MatrixHttpClient (REQ-164) { errcode: 'M_FORBIDDEN', error: 'Unknown room' }
Executing (default): SELECT `id`, `lineMode`, `lineHookFrom`, `lineTo`, `matrixTo`, `createdTime`, `updatedTime` FROM `room_map` AS `room_map` WHERE `room_map`.`lineHookFrom` = 'C7d95034fd3e3ec445aea8c48eff42a9e' LIMIT 1;
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.pairConfirm (/pub/git/matrix-line-bridge/src/providers/line/listener/message/text.ts:86:63)
    at async Object.exports.default [as text] (/pub/git/matrix-line-bridge/src/providers/line/listener/message/text.ts:148:20)
    at async Promise.all (index 0)
    at async eventsDispatcher (/pub/git/matrix-line-bridge/src/providers/line/listener/handler.ts:44:22)
Executing (default): SELECT `id`, `lineMode`, `lineHookFrom`, `lineTo`, `matrixTo`, `createdTime`, `updatedTime` FROM `room_map` AS `room_map` WHERE `room_map`.`lineHookFrom` = 'C7d95034fd3e3ec445aea8c48eff42a9e' LIMIT 1;
Executing (default): SELECT `id`, `lineMode`, `lineHookFrom`, `lineTo`, `matrixTo`, `createdTime`, `updatedTime` FROM `room_map` AS `room_map` WHERE `room_map`.`matrixTo` = '!YxhykoFGQAHrdkompB:domo.ddns.net' AND `room_map`.`lineMode` = 'push' LIMIT 1;
MatrixHttpClient (REQ-166) { errcode: 'M_FORBIDDEN', error: 'Unknown room' }
Executing (default): SELECT `id`, `lineMode`, `lineHookFrom`, `lineTo`, `matrixTo`, `createdTime`, `updatedTime` FROM `room_map` AS `room_map` WHERE `room_map`.`lineHookFrom` = 'C7d95034fd3e3ec445aea8c48eff42a9e' LIMIT 1;
```

**Comment by supersonictw** [comment]
Arona did it. https://github.com/web-tech-tw/arona/pull/18
